import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newContext({ ignoreHTTPSErrors: true, viewport:{width:1600,height:1100} });
const pg = await p.newPage();
await pg.goto('https://localhost:5198/?v2', { waitUntil:'commit' });
await pg.waitForSelector('section.bg-gradient-to-b button[aria-label*="2568"]', { timeout:6000 });
await pg.waitForTimeout(300);
await pg.screenshot({ path:'/private/tmp/claude-501/-Users-joeos-beond-dashboard/a5a8b3b1-cab5-4a7f-905b-15b283760d7c/scratchpad/v-collapsed.png' });
await pg.waitForTimeout(1200);
await pg.screenshot({ path:'/private/tmp/claude-501/-Users-joeos-beond-dashboard/a5a8b3b1-cab5-4a7f-905b-15b283760d7c/scratchpad/v-tour.png' });
await b.close();
